blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blogs, name='blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):

    image = models.ImageField(upload_to='portfolio/public/images/blog/')
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):

    title = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    image = models.ImageField(upload_to='portfolio/public/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.
def blogs(request):
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blogs/index.html', {'blogs':blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blogs/detail.html', {'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# home page
def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/index.html', {'projects':projects})

blog/templates/blogs/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}
<style>
    #blog {
        padding: 10px;
    }
</style>
<div id="blog">
    <img class="card-img-top" src="{{ blog.image.url }}" height="500" loading="lazy" alt="">
    <h2><strong>{{ blog.title }}</strong></h2>
    <p>{{ blog.date|date:'F jS Y' }}</p>
    <p>{{ blog.description|safe }}</p>
</div>
<script>
    window.addEventListener('load', (event) => {
        // set active navitem blog
        document.getElementById('navitem-blogs').classList.add('active');
    });
</script>
{% endblock %}

blog/templates/blogs/index.html
{% extends 'portfolio/base.html' %}

{% block content %}
<style>
    div#blog_div {
        padding: 10px;
    }
    div#blog_div h2 {
        padding: 10px;
        text-align: center;
    }
    div#blog_row {
        margin: 10px;
    }
    div.blog_col {
        padding: 0px !important;
    }
    div.card.blogs {
        margin: 10px;
        height: 420px;
        min-width: 335px;
        cursor: pointer;
    }
    div.blogs p.blog_date {
        position: absolute;
        bottom: 0;
    }
</style>
<div id="blog_div">
    <h2><strong>IAMKAnche Blog List</strong></h2>
    <div class="row" id="blog_row">
        {% for blog in blogs %}
        <div class="col blog_col">
            <div class="card blogs"  id="{{ blog.id }}" data-blog_link = "{% url 'blog:detail' blog.id %}">
                <img class="card-img-top" src="{{ blog.image.url }}" width="400" height="224" loading="lazy" alt="">
                <div class="card-body">
                    <h5 class="card-title"><strong>{{ blog.title }}</strong></h5>
                    <p class="card-text">{{ blog.description|striptags|truncatechars:100 }}</p>
                    <p class="card-text blog_date"><small class="text-muted">{{ blog.date|date:'M d Y'|upper }}</small></p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<script>
    window.addEventListener('load', (event) => {
        // set active navitem blog
        document.getElementById('navitem-blogs').classList.add('active');
        // mouseover and click
        document.querySelectorAll('.blogs').forEach(blog => {
            // mouse over
            blog.addEventListener('mouseover', (event) => {
                blog.style.boxShadow = '-3px 0px 50px -2px rgba(0, 0, 0, 0.5)';
            });
             // mouse out
            blog.addEventListener('mouseout', (event) => {
                blog.style.removeProperty('box-shadow');
            });
            // mouse click
            blog.addEventListener('click', (event) => {
                location.href = blog.getAttribute('data-blog_link');
            });
        });
    });
</script>
{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">

        <title>IAMKAnche</title>
    </head>
    <style>
        div#main_body {
            margin-top: 10px;
            margin-bottom: 30px;
            padding-top: 10px;
            padding-bottom: 50px;
            box-shadow: -3px 0px 50px -2px rgba(0, 0, 0, 0.5);
        }
        div#footer {
            position: fixed;
            height: 30px;
            width: 100%;
            bottom: 0;
            text-align: center;
            padding: 3px;
            color: #fff;
            font-weight: bold;
            background-color: #343a40!important;
        }
        div#footer a {
            color: white;
            margin: 5px;
        }
        div#footer i.zmdi {
            height: 20px !important;
            width: 20px !important;
        }
    </style>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="{% static 'portfolio/profile.jpg' %}" width="50" height="50" style="border-radius: 50%;">
                    <b>IAMKAnche</b>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item" id="navitem-blogs">
                            <a class="nav-link" href="{% url 'blog:blogs' %}"><b>BLOG</b></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container" id="main_body">
            {% block content %}{% endblock %}
        </div>
        <div id="footer">
            <a href="https://github.com" target="_blank"><i class="zmdi zmdi-github zmdi-hc-lg"></i></a>
            <a href="https://twitter.com" target="_blank"><i class="zmdi zmdi-twitter zmdi-hc-lg"></i></a>
            <a href="https://www.linkedin.com" target="_blank"><i class="zmdi zmdi-linkedin-box zmdi-hc-lg"></i></a>
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>

portfolio/templates/portfolio/index.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}
<style>
div#project_div {
    padding: 10px;
}
div#project_div h2 {
    padding: 10px;
    text-align: center;
}
div#project_row {
    margin: 10px;
}
div.card.projects {
    margin: 10px;
    height: 375px;
    min-width: 335px;
    cursor: pointer;
}
div.project_col {
    padding: 0px !important;
}
</style>
<div id="project_div">
    <h2><strong>IAMKAnche Project List</strong></h2>
    <div class="row" id="project_row">
        {% for project in projects %}
        <div class="col project_col">
            <div class="card projects"  id="{{ project.id }}" data-project_link = "{{ project.url }}">
                <img class="card-img-top" src="{{ project.image.url }}" width="400" height="224" loading="lazy" alt="">
                <div class="card-body">
                    <h5 class="card-title"><strong>{{ project.title }}</strong></h5>
                    <p class="card-text">{{ project.description|truncatechars:50 }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<script>
    window.addEventListener('load', (event) => {
        // mouseover and click
        document.querySelectorAll('.projects').forEach(project => {
            // mouse over
            project.addEventListener('mouseover', (event) => {
                project.style.boxShadow = '-3px 0px 50px -2px rgba(0, 0, 0, 0.5)';
            });
             // mouse out
            project.addEventListener('mouseout', (event) => {
                project.style.removeProperty('box-shadow');
            });
            // mouse click
            project.addEventListener('click', (event) => {
                if (project.getAttribute('data-project_link'))
                    window.open(project.getAttribute('data-project_link'), '_blank');
                return true;
            });
        });
    });
</script>
{% endblock %}